-- Create a table to store character likes
create table if not exists character_likes (
  id bigint generated by default as identity primary key,
  character_id uuid references characters(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(character_id, user_id)
);

-- Enable RLS
alter table character_likes enable row level security;

-- Policies
-- Everyone can view likes
create policy "Likes are viewable by everyone"
  on character_likes for select
  using ( true );

-- Authenticated users can insert their own likes
create policy "Users can insert their own likes"
  on character_likes for insert
  with check ( auth.uid() = user_id );

-- Users can delete their own likes
create policy "Users can delete their own likes"
  on character_likes for delete
  using ( auth.uid() = user_id );
